-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: check-added-large-files
        language_version: python3
    -   id: check-ast
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: check-json
        language_version: python3
    -   id: detect-private-key
        language_version: python3
    #-   id: detect-aws-credentials
    #    language_version: python3
    #-   id: flake8
    #    language_version: python3
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      args: [-l 79]
